function Grad_U = Grad_U(R,U_0_alpha_B,r_alpha_B_x,r_alpha_B_y)
%GRAD_U
%    GRAD_U = GRAD_U(R,U_0_ALPHA_B,R_ALPHA_B_X,R_ALPHA_B_Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    19-Apr-2018 14:30:49

t2 = 1.0./R;
t3 = abs(r_alpha_B_x);
t4 = abs(r_alpha_B_y);
t5 = t3.^2;
t6 = t4.^2;
t7 = t5+t6;
t8 = sqrt(t7);
t9 = exp(-t2.*t8);
t10 = 1.0./sqrt(t7);
Grad_U = [-U_0_alpha_B.*t2.*t3.*t9.*t10.*sign(r_alpha_B_x);-U_0_alpha_B.*t2.*t4.*t9.*t10.*sign(r_alpha_B_y)];
